Add option to skip tflint warn

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -37,6 +37,10 @@ on:
         type: string
         default: ""
         required: false
+      skip_tflint_warn:
+        description: Do not fail for tflint warning
+        type: boolean
+        default: false
     secrets:
       TFE_TOKEN:
         description: Terraform Cloud Token
@@ -46,8 +50,8 @@ env:
   TF_IN_AUTOMATION: "true"
 
 jobs:
-  fmt-lint-validate:
-    name: Format, Lint and Validate
+  fmt-validate:
+    name: Format and Validate
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -73,17 +77,6 @@ jobs:
           terraform_version: latest
           cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
 
-      - name: Cache TFlint
-        uses: actions/cache@v2
-        with:
-          path: /home/runner/.tflint.d/plugins
-          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
-
-      - name: Setup TFLint
-        uses: terraform-linters/setup-tflint@v2
-        with:
-          tflint_version: latest
-
       - name: Pre-init Hook
         run: ${{ inputs.pre_init_hook }}
 
@@ -93,7 +86,7 @@ jobs:
       - name: Precommit Skips
         id: precommit_skips
         run: |
-          SKIPS="markdown-link-check,terraform_docs,terraform_tfsec,checkov,terraform_checkov"
+          SKIPS="tflint,terraform_tflint,markdown-link-check,terraform_docs,terraform_tfsec,checkov,terraform_checkov"
           if [ "${branch}" == "${main_branch}" ];then
               SKIPS="${SKIPS},no-commit-to-branch"
           fi
@@ -116,40 +109,32 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
       - run: terraform -v
 
-  # lint:
-  #   name: Linting
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 1
-  #         submodules: ${{ inputs.enable_submodules }}
+  lint:
+    name: Linting
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+          submodules: ${{ inputs.enable_submodules }}
 
-<<<<<<< HEAD
+
       - run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"
       - name: Cache Terraform
         uses: actions/cache@v3
         with:
           path: ${{ env.TF_PLUGIN_CACHE_DIR }}
           key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
-=======
-  #     - run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"
-  #     - name: Cache Terraform
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
-  #         key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
->>>>>>> bca88fc (Use pre-commit tflint)
 
-  #     - name: Setup Terraform
-  #       uses: hashicorp/setup-terraform@v2
-  #       with:
-  #         terraform_version: latest
-  #         cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: latest
+          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
 
-  #     - name: Terraform init
-  #       run: terraform init
+      - name: Terraform init
+        run: terraform init
 
       - name: Cache TFlint
         uses: actions/cache@v3
@@ -157,16 +142,32 @@ jobs:
           path: /home/runner/.tflint.d/plugins
           key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
 
-  #     - name: Run tflint with review comment on PR
-  #       uses: reviewdog/action-tflint@master
-  #       with:
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         tflint_init: true
-  #         filter_mode: "nofilter"
-  #         reporter: github-pr-review
-  #         # tflint_rulesets: "aws"
-  #         flags: --module
-  #         level: info
+      - name: Setup TFLint
+        uses: terraform-linters/setup-tflint@v2
+        with:
+          tflint_version: latest
+
+      - name: Run TFLint
+        id: tflint
+        continue-on-error: true
+        run: |
+          pre-commit run terraform_tflint --all-files
+          exit_code=$?
+          echo "::set-output name=return-code::${tflint_return}"
+
+      - name: Check status code
+        if: success() || failure ()
+        run: |
+          tflint_return=${{ steps.tflint.outputs.return-code }}
+          skip_warn=${{ inputs.skip_tflint_warn }}
+          if [ "$tflint_return" -eq 0 ]; then
+            echo "TFLint correctly returned failure: ${tflint_return}"
+          elif [ $skip_warn && $tflint_return -eq 2 ]; then
+            echo "TFLint warnings found and skipped."
+          else
+            echo "TFLint returned ${reviewdog_return}, expected '0'. Failing..."
+            exit 1
+          fi
 
   security:
     name: Security Checks
